#!/usr/bin/env node
import { execFileSync, execSync, spawn } from "node:child_process"
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync
} from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import puppeteer from "puppeteer"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const rootDir = path.resolve(__dirname, "..")

const buildDir = path.join(rootDir, ".output", "chrome-mv3")
const assetsDir = path.join(rootDir, "assets")
const localesDir = path.join(buildDir, "_locales")
const outDir = path.join(rootDir, "store-assets")
const globalScreenshotsDir = path.join(outDir, "localized", "en", "screenshots")
const localizedDir = path.join(outDir, "localized")
const tmpDir = path.join(outDir, ".tmp")

const gameIcons = [
  "tango",
  "queens",
  "pinpoint",
  "crossclimb",
  "sudoku",
  "zip",
  "patches",
  "wend"
] as const

function q(value: string | number | boolean): string {
  return `'${String(value).replace(/'/g, "'\\''")}'`
}

function run(command: string): void {
  execSync(command, { stdio: "inherit" })
}

function asyncRun(command: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn("sh", ["-c", command], { stdio: "inherit" })
    child.on("close", (code) => {
      if (code === 0) resolve()
      else reject(new Error(`Process exited with code ${code}`))
    })
    child.on("error", reject)
  })
}

function hasTool(name: string): boolean {
  try {
    execFileSync("which", [name], { stdio: "ignore" })
    return true
  } catch {
    return false
  }
}

function _ensureTool(name: string): void {
  if (!hasTool(name)) {
    throw new Error(
      `Required tool '${name}' is not installed or not available in PATH.`
    )
  }
}

function resolveImageMagickCmd(): string {
  return hasTool("magick") ? "magick" : "convert"
}

function ensureDir(dirPath: string): void {
  mkdirSync(dirPath, { recursive: true })
}

function renderSvg(
  svgPath: string,
  pngPath: string,
  width: number,
  height: number
): void {
  execFileSync(
    "rsvg-convert",
    ["-w", String(width), "-h", String(height), "-o", pngPath, svgPath],
    {
      stdio: "inherit"
    }
  )
}

const imageMagickCmd = resolveImageMagickCmd()

function renderPaddedSvg(
  svgPath: string,
  pngPath: string,
  totalSize: number,
  artworkSize: number
): void {
  ensureDir(tmpDir)
  const tempPng = path.join(
    tmpDir,
    `temp-${path.basename(pngPath)}-${artworkSize}.png`
  )
  renderSvg(svgPath, tempPng, artworkSize, artworkSize)

  execFileSync(
    imageMagickCmd,
    [
      tempPng,
      "-background",
      "none",
      "-gravity",
      "center",
      "-extent",
      `${totalSize}x${totalSize}`,
      pngPath
    ],
    { stdio: "inherit" }
  )

  rmSync(tempPng, { force: true })
}

// Load store asset translations generated by apply-translations.ts
const translationsPath = path.join(__dirname, "store-assets-translations.json")
if (!existsSync(translationsPath)) {
  throw new Error(
    `Translations file not found at ${translationsPath}. Please run scripts/apply-translations.ts first.`
  )
}
const translations = JSON.parse(readFileSync(translationsPath, "utf8"))

const promoTranslations: Record<
  string,
  { title: string; line1: string; line2: string }
> = translations.promoTranslations

const marqueeTranslations: Record<
  string,
  { title: string; line1: string; line2: string }
> = translations.marqueeTranslations

const compiledNameMap: Record<string, string> = translations.extensionNameMap
const compiledSubtitleMap: Record<string, string> = translations.subtitleMap
const compiledScene3 = translations.scene3
const compiledScene4 = translations.scene4
const compiledScene6 = translations.scene6
const compiledDescriptions: Record<string, string> = translations.descriptions

// --- Locale Utility Helpers ---
interface LocaleMessage {
  message?: string
  description?: string
}

interface LocaleMessages {
  [key: string]: LocaleMessage | undefined
}

function readLocaleMessages(locale: string): LocaleMessages {
  const localeFile = path.join(localesDir, locale, "messages.json")
  if (!existsSync(localeFile)) {
    return {}
  }
  try {
    return JSON.parse(readFileSync(localeFile, "utf8")) as LocaleMessages
  } catch {
    return {}
  }
}

function getMessageValue(messages: LocaleMessages, key: string): string {
  const value = messages?.[key]?.message
  return typeof value === "string" ? value : ""
}

function cleanText(value: string): string {
  return value.replace(/\s+/g, " ").trim()
}

function truncateText(value: string, maxLength: number): string {
  if (value.length <= maxLength) {
    return value
  }
  return `${value.slice(0, Math.max(0, maxLength - 1)).trimEnd()}…`
}

// Maps locale base language to a representative Unicode codepoint in its script.
// Used alongside Latin U+0041 to find fonts that support BOTH Latin and the
// target script via fc-list, avoiding fallback Latin-only or script-only fonts.
const LOCALE_CHARSET: Record<string, string> = {
  am: "1200", // Ethiopic: ሀ U+1200
  ar: "0627",
  fa: "0627", // Arabic: ا U+0627
  bg: "0410",
  ru: "0410",
  sr: "0410",
  uk: "0410", // Cyrillic: А U+0410
  bn: "0985", // Bengali: অ U+0985
  el: "03B1", // Greek: α U+03B1
  gu: "0A85", // Gujarati: અ U+0A85
  he: "05D0", // Hebrew: א U+05D0
  hi: "0905",
  mr: "0905", // Devanagari: अ U+0905
  ja: "4E2D", // Japanese: 中 U+4E2D (CJK)
  kn: "0C85", // Kannada: ಅ U+0C85
  ko: "AC00", // Korean: 가 U+AC00
  ml: "0D05", // Malayalam: അ U+0D05
  ta: "0B85", // Tamil: அ U+0B85
  te: "0C05", // Telugu: అ U+0C05
  th: "0E01", // Thai: ก U+0E01
  zh: "4E2D" // Chinese: 中 U+4E2D (CJK)
}

function resolveFontPathForLocale(locale: string): string {
  const lang = locale.split("_")[0].toLowerCase()
  const scriptChar = LOCALE_CHARSET[lang]
  if (!scriptChar) {
    return ""
  }
  try {
    // Query fc-list for fonts that contain BOTH Latin 'A' (U+0041) and the
    // representative script character, ensuring the font supports both.
    const result = execFileSync(
      "fc-list",
      [`:charset=0041 ${scriptChar}`, "file"],
      { encoding: "utf8" }
    ).trim()
    if (!result) return ""

    // Take the first result, filtering out decorative/icon fonts
    for (const line of result.split("\n")) {
      const fontPath = line.split(":")[0].trim()
      if (
        fontPath &&
        existsSync(fontPath) &&
        !fontPath.includes("NerdFont") &&
        !fontPath.includes("Caskaydia")
      ) {
        return fontPath
      }
    }
    return ""
  } catch {
    return ""
  }
}

// --- Mock Solve History Generator ---
interface GameSolveInfo {
  solved: boolean
  solvedAt?: string
  time: number
}

interface DaySolveInfo {
  [game: string]: GameSolveInfo
}

interface SolveHistory {
  [date: string]: DaySolveInfo
}

function getLocalDateString(offsetDays: number = 0): string {
  const d = new Date(Date.now() - offsetDays * 24 * 60 * 60 * 1000)
  const year = d.getFullYear()
  const month = String(d.getMonth() + 1).padStart(2, "0")
  const day = String(d.getDate()).padStart(2, "0")
  return `${year}-${month}-${day}`
}

function generateMockSolveHistory(): SolveHistory {
  const todayStr = getLocalDateString(0)
  const yesterdayStr = getLocalDateString(1)
  const dayBeforeStr = getLocalDateString(2)

  return {
    [dayBeforeStr]: {
      crossclimb: {
        solved: true,
        solvedAt: `${dayBeforeStr}T23:01:28.803Z`,
        time: 203
      },
      patches: {
        solved: true,
        solvedAt: `${dayBeforeStr}T23:00:54.135Z`,
        time: 2
      },
      pinpoint: {
        solved: true,
        solvedAt: `${dayBeforeStr}T23:00:16.358Z`,
        time: 1
      },
      queens: {
        solved: true,
        solvedAt: `${dayBeforeStr}T23:01:28.379Z`,
        time: 4
      },
      sudoku: {
        solved: true,
        solvedAt: `${dayBeforeStr}T23:01:25.733Z`,
        time: 3
      },
      tango: {
        solved: true,
        solvedAt: `${dayBeforeStr}T23:01:27.383Z`,
        time: 4
      },
      wend: {
        solved: true,
        solvedAt: `${dayBeforeStr}T23:01:27.800Z`,
        time: 4
      },
      zip: {
        solved: true,
        solvedAt: `${dayBeforeStr}T23:01:26.288Z`,
        time: 248
      }
    },
    [yesterdayStr]: {
      crossclimb: {
        solved: true,
        solvedAt: `${yesterdayStr}T07:26:06.460Z`,
        time: 18
      },
      patches: {
        solved: true,
        solvedAt: `${yesterdayStr}T07:21:58.006Z`,
        time: 4
      },
      pinpoint: {
        solved: true,
        solvedAt: `${yesterdayStr}T07:24:27.684Z`,
        time: 4
      },
      queens: {
        solved: true,
        solvedAt: `${yesterdayStr}T07:22:33.075Z`,
        time: 3
      },
      sudoku: {
        solved: true,
        solvedAt: `${yesterdayStr}T07:21:50.275Z`,
        time: 1
      },
      tango: {
        solved: true,
        solvedAt: `${yesterdayStr}T07:22:16.477Z`,
        time: 2
      },
      wend: {
        solved: true,
        solvedAt: `${yesterdayStr}T07:22:18.500Z`,
        time: 3
      },
      zip: {
        solved: true,
        solvedAt: `${yesterdayStr}T07:22:07.854Z`,
        time: 2
      }
    },
    [todayStr]: {
      patches: {
        solved: true,
        time: 376,
        solvedAt: `${todayStr}T08:26:36.253Z`
      },
      pinpoint: {
        solved: true,
        solvedAt: `${todayStr}T10:09:08.440Z`,
        time: 9
      },
      sudoku: {
        solved: true,
        time: 7,
        solvedAt: `${todayStr}T09:55:41.476Z`
      },
      tango: {
        solved: true,
        solvedAt: `${todayStr}T09:55:50.067Z`,
        time: 2
      },
      zip: {
        solved: true,
        time: 259,
        solvedAt: `${todayStr}T09:55:32.936Z`
      },
      crossclimb: {
        solved: true,
        time: 447,
        solvedAt: `${todayStr}T10:49:55.224Z`
      },
      queens: {
        solved: true,
        time: 2,
        solvedAt: `${todayStr}T10:50:29.857Z`
      },
      wend: {
        solved: true,
        time: 5,
        solvedAt: `${todayStr}T10:51:04.120Z`
      }
    }
  }
}

// Generate active progress history (today partially solved)
function generateMockActiveHistory(): SolveHistory {
  const todayStr = getLocalDateString(0)
  const base = generateMockSolveHistory()

  base[todayStr] = {
    patches: {
      solved: true,
      time: 120,
      solvedAt: `${todayStr}T08:26:36.253Z`
    },
    pinpoint: {
      solved: true,
      solvedAt: `${todayStr}T10:09:08.440Z`,
      time: 9
    },
    sudoku: {
      solved: false,
      time: 0
    },
    tango: {
      solved: true,
      solvedAt: `${todayStr}T09:55:50.067Z`,
      time: 2
    },
    zip: {
      solved: true,
      time: 259,
      solvedAt: `${todayStr}T09:55:32.936Z`
    },
    crossclimb: {
      solved: false,
      time: 0
    },
    queens: {
      solved: true,
      time: 2,
      solvedAt: `${todayStr}T10:50:29.857Z`
    },
    wend: {
      solved: false,
      time: 0
    }
  }

  return base
}

// Render SVGs to temporary PNGs for composite use
function prepIconRenders(): void {
  ensureDir(tmpDir)

  renderSvg(
    path.join(assetsDir, "icon.svg"),
    path.join(tmpDir, "icon-96.png"),
    96,
    96
  )
  renderSvg(
    path.join(assetsDir, "icon.svg"),
    path.join(tmpDir, "icon-140.png"),
    140,
    140
  )
  renderSvg(
    path.join(assetsDir, "icon.svg"),
    path.join(tmpDir, "icon-170.png"),
    170,
    170
  )
  renderSvg(
    path.join(assetsDir, "icon.svg"),
    path.join(tmpDir, "icon-300.png"),
    300,
    300
  )

  for (const game of gameIcons) {
    renderSvg(
      path.join(assetsDir, `${game}.svg`),
      path.join(tmpDir, `${game}-220.png`),
      220,
      220
    )
    renderSvg(
      path.join(assetsDir, `${game}.svg`),
      path.join(tmpDir, `${game}-148.png`),
      148,
      148
    )
    renderSvg(
      path.join(assetsDir, `${game}.svg`),
      path.join(tmpDir, `${game}-120.png`),
      120,
      120
    )
  }
}

// Generate the 128x128 store icon
function generateStoreIcon(): void {
  const output = path.join(outDir, "store-icon-128.png")
  renderSvg(path.join(assetsDir, "icon.svg"), output, 128, 128)
}

// Generate extension icons for various sizes (16, 32, 48, 128)
function generateExtensionIcons(): void {
  const publicDir = path.join(rootDir, "public")
  const publicAssetsDir = path.join(publicDir, "assets")

  ensureDir(publicDir)
  ensureDir(publicAssetsDir)

  const iconTypes = [
    { name: "icon", svg: "icon.svg" },
    { name: "icon-dark", svg: "icon-dark.svg" },
    { name: "icon-light", svg: "icon-light.svg" }
  ]

  for (const { name, svg } of iconTypes) {
    const svgPath = path.join(assetsDir, svg)

    // Padded sizes for 16, 32, 48, 128 (artwork size is 75% of total size)
    for (const size of [16, 32, 48, 128]) {
      const outPublicAsset = path.join(publicAssetsDir, `${name}-${size}.png`)
      const artworkSize = Math.round(size * 0.75)
      renderPaddedSvg(svgPath, outPublicAsset, size, artworkSize)

      // Also generate in the root assets directory so they are present in the source folder
      const outRootAsset = path.join(assetsDir, `${name}-${size}.png`)
      renderPaddedSvg(svgPath, outRootAsset, size, artworkSize)
    }

    // Also copy / generate standard name.png at 128x128 padded (artwork size 96)
    const outPublicAssetStandard = path.join(publicAssetsDir, `${name}.png`)
    renderPaddedSvg(svgPath, outPublicAssetStandard, 128, 96)

    // And sync to the root assets directory
    const outRootAssetStandard = path.join(assetsDir, `${name}.png`)
    renderPaddedSvg(svgPath, outRootAssetStandard, 128, 96)
  }

  // Finally, the extension's root icon.png in public/ must be the 128x128 padded
  const outPublicRootIcon = path.join(publicDir, "icon.png")
  renderPaddedSvg(path.join(assetsDir, "icon.svg"), outPublicRootIcon, 128, 96)
}

// Generate 440x280 small promo tile
async function generatePromoSmall(
  localeCode: string = "global"
): Promise<void> {
  const isGlobal = localeCode === "global"
  const actualLocale = isGlobal ? "en" : localeCode

  const targetDir = isGlobal
    ? path.join(outDir, "global")
    : path.join(outDir, "localized", actualLocale)

  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true })
  }

  const output = path.join(targetDir, "small-promo-440x280.jpg")
  const outputPng = path.join(targetDir, "small-promo-440x280.png")

  const screenshotPath = isGlobal
    ? path.join(globalScreenshotsDir, "screenshot-1.jpg")
    : path.join(
        outDir,
        "localized",
        actualLocale,
        "screenshots",
        "screenshot-1.jpg"
      )

  const translation = promoTranslations[actualLocale] || promoTranslations.en
  const localeFontPath = resolveFontPathForLocale(actualLocale)

  if (!existsSync(screenshotPath)) {
    console.log(
      `Screenshot-1 not found for ${actualLocale}, generating base Small Promo without screenshot...`
    )
    const cmdArgs = [
      imageMagickCmd,
      "-size",
      "440x280",
      q("gradient:#0a66c2-#1e3a8a"),
      "\\(",
      "-size",
      "440x280",
      "xc:none",
      "-fill",
      q("rgba(255,255,255,0.07)"),
      "-draw",
      q("circle 370,18 560,218"),
      "\\)",
      "-composite",
      "\\(",
      q(path.join(tmpDir, "icon-170.png")),
      "\\)",
      "-gravity",
      "west",
      "-geometry",
      "+34+0",
      "-composite",
      "\\(",
      q(path.join(tmpDir, "tango-120.png")),
      "\\)",
      "-gravity",
      "east",
      "-geometry",
      "+30-56",
      "-composite",
      "\\(",
      q(path.join(tmpDir, "queens-120.png")),
      "\\)",
      "-gravity",
      "east",
      "-geometry",
      "+90+36",
      "-composite",
      ...(localeFontPath ? ["-font", q(localeFontPath)] : []),
      "-strip"
    ]

    await Promise.all([
      asyncRun([...cmdArgs, "-quality", "100", q(output)].join(" ")),
      asyncRun([...cmdArgs, q(outputPng)].join(" "))
    ])
    return
  }

  console.log(
    `Generating premium Small Promo Tile (${actualLocale}) with embedded browser screenshot...`
  )
  const premiumArgs = [
    imageMagickCmd,
    "-size",
    "440x280",
    q("gradient:#0a66c2-#0f172a"),
    // Glowing decorative elements
    "\\(",
    "-size",
    "440x280",
    "xc:none",
    "-fill",
    q("rgba(255,255,255,0.05)"),
    "-draw",
    q("circle 380,180 440,240"),
    "\\)",
    "-composite",
    // Embed popup screenshot
    "\\(",
    q(screenshotPath),
    "-resize",
    "166x",
    "-bordercolor",
    q("rgba(255,255,255,0.15)"),
    "-border",
    "1",
    "\\)",
    "-gravity",
    "east",
    "-geometry",
    "+36+0",
    "-composite",
    // Embed extension icon logo
    "\\(",
    q(path.join(tmpDir, "icon-96.png")),
    "-resize",
    "60x60",
    "\\)",
    "-gravity",
    "west",
    "-geometry",
    "+36-36",
    "-composite",
    // Render clean, modern typography
    ...(localeFontPath ? ["-font", q(localeFontPath)] : []),
    "-pointsize",
    "22",
    "-fill",
    "white",
    "-gravity",
    "northwest",
    "-annotate",
    "+36+154",
    q(translation.title),
    "-pointsize",
    "11",
    "-fill",
    q("#94a3b8"),
    "-annotate",
    "+36+186",
    q(translation.line1),
    "-annotate",
    "+36+202",
    q(translation.line2),
    "-strip"
  ]

  await Promise.all([
    asyncRun([...premiumArgs, "-quality", "100", q(output)].join(" ")),
    asyncRun([...premiumArgs, q(outputPng)].join(" "))
  ])
}

// Generate 1400x560 marquee promo tile
async function generatePromoMarquee(
  localeCode: string = "global"
): Promise<void> {
  const isGlobal = localeCode === "global"
  const actualLocale = isGlobal ? "en" : localeCode

  const targetDir = isGlobal
    ? path.join(outDir, "global")
    : path.join(outDir, "localized", actualLocale)

  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true })
  }

  const output = path.join(targetDir, "marquee-promo-1400x560.jpg")
  const outputPng = path.join(targetDir, "marquee-promo-1400x560.png")

  const popupPath = isGlobal
    ? path.join(globalScreenshotsDir, "screenshot-1.jpg")
    : path.join(
        outDir,
        "localized",
        actualLocale,
        "screenshots",
        "screenshot-1.jpg"
      )
  const dashboardPath = isGlobal
    ? path.join(globalScreenshotsDir, "screenshot-3.jpg")
    : path.join(
        outDir,
        "localized",
        actualLocale,
        "screenshots",
        "screenshot-3.jpg"
      )

  const translation =
    marqueeTranslations[actualLocale] || marqueeTranslations.en
  const localeFontPath = resolveFontPathForLocale(actualLocale)

  if (!existsSync(popupPath) || !existsSync(dashboardPath)) {
    console.log(
      `Screenshots not found for ${actualLocale}, generating base Marquee Promo without screenshots...`
    )
    const baseArgs = [
      imageMagickCmd,
      "-size",
      "1400x560",
      q("gradient:#0a66c2-#0f172a"),
      "\\(",
      "-size",
      "1400x560",
      "xc:none",
      "-fill",
      q("rgba(255,255,255,0.06)"),
      "-draw",
      q("circle 1180,-30 1620,420"),
      "\\)",
      "-composite",
      "\\(",
      q(path.join(tmpDir, "icon-300.png")),
      "\\)",
      "-gravity",
      "west",
      "-geometry",
      "+120+0",
      "-composite",
      "\\(",
      q(path.join(tmpDir, "tango-220.png")),
      "\\)",
      "-gravity",
      "east",
      "-geometry",
      "+280-120",
      "-composite",
      "\\(",
      q(path.join(tmpDir, "pinpoint-220.png")),
      "\\)",
      "-gravity",
      "east",
      "-geometry",
      "+120+0",
      "-composite",
      "\\(",
      q(path.join(tmpDir, "queens-220.png")),
      "\\)",
      "-gravity",
      "east",
      "-geometry",
      "+340+140",
      "-composite",
      "\\(",
      q(path.join(tmpDir, "zip-220.png")),
      "\\)",
      "-gravity",
      "east",
      "-geometry",
      "+30+150",
      "-composite",
      "\\(",
      q(path.join(tmpDir, "wend-220.png")),
      "\\)",
      "-gravity",
      "east",
      "-geometry",
      "+60-160",
      "-composite",
      ...(localeFontPath ? ["-font", q(localeFontPath)] : []),
      "-strip"
    ]

    await Promise.all([
      asyncRun([...baseArgs, "-quality", "100", q(output)].join(" ")),
      asyncRun([...baseArgs, q(outputPng)].join(" "))
    ])
    return
  }

  console.log(
    `Generating premium Marquee Promo Tile (${actualLocale}) with layered screenshot mockups...`
  )
  const premiumArgs = [
    imageMagickCmd,
    "-size",
    "1400x560",
    q("gradient:#0a66c2-#0f172a"),
    // Glowing decorative circles
    "\\(",
    "-size",
    "1400x560",
    "xc:none",
    "-fill",
    q("rgba(255,255,255,0.04)"),
    "-draw",
    q("circle 1150,280 1280,360"),
    "\\)",
    "-composite",
    // Layer the large Dashboard screenshot in the background (center-right)
    "\\(",
    q(dashboardPath),
    "-resize",
    "560x",
    "-bordercolor",
    q("rgba(255,255,255,0.12)"),
    "-border",
    "2",
    "\\)",
    "-gravity",
    "east",
    "-geometry",
    "+130-10",
    "-composite",
    // Layer the smaller Popup screenshot overlapping it in the foreground
    "\\(",
    q(popupPath),
    "-resize",
    "210x",
    "-bordercolor",
    q("rgba(255,255,255,0.2)"),
    "-border",
    "2",
    "\\)",
    "-gravity",
    "east",
    "-geometry",
    "+64+76",
    "-composite",
    // Brand logo icon on the left (shifted slightly up to increase vertical margin)
    "\\(",
    q(path.join(tmpDir, "icon-300.png")),
    "-resize",
    "120x120",
    "\\)",
    "-gravity",
    "west",
    "-geometry",
    "+90-135",
    "-composite",
    // Premium Titles & Text overlay (shifted slightly down to give breathing room under the logo)
    ...(localeFontPath ? ["-font", q(localeFontPath)] : []),
    "-pointsize",
    "52",
    "-fill",
    "white",
    "-gravity",
    "northwest",
    "-annotate",
    "+90+245",
    q(translation.title),
    "-pointsize",
    "18",
    "-fill",
    q("#94a3b8"),
    "-annotate",
    "+90+320",
    q(translation.line1),
    "-pointsize",
    "13",
    "-fill",
    q("#38bdf8"),
    "-annotate",
    "+90+360",
    q(translation.line2),
    "-strip"
  ]

  await Promise.all([
    asyncRun([...premiumArgs, "-quality", "100", q(output)].join(" ")),
    asyncRun([...premiumArgs, q(outputPng)].join(" "))
  ])
}

// --- Puppeteer Screenshot Engine ---
async function captureScreenshots(locale: string = "en"): Promise<void> {
  console.log(`\nGenerating screenshots for locale: [${locale.toUpperCase()}]`)

  if (!existsSync(buildDir)) {
    console.log("No built extension found. Building extension...")
    await asyncRun("npx wxt build")
  }

  const chromeLang = locale.replace("_", "-")

  const browser = await puppeteer.launch({
    headless: true,
    executablePath: "/usr/bin/chromium",
    args: [
      `--disable-extensions-except=${buildDir}`,
      `--load-extension=${buildDir}`,
      `--lang=${chromeLang}`,
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-gpu",
      "--disable-dev-shm-usage",
      "--single-process"
    ]
  })

  try {
    const workerTarget = await browser.waitForTarget(
      (target) =>
        target.type() === "service_worker" ||
        target.url().startsWith("chrome-extension://"),
      { timeout: 10000 }
    )
    const extensionId = new URL(workerTarget.url()).hostname

    const popupUrl = `chrome-extension://${extensionId}/popup.html`
    const dashboardUrl = `chrome-extension://${extensionId}/tabs/dashboard.html`

    const saveDir = path.join(localizedDir, locale, "screenshots")
    ensureDir(saveDir)

    const page = await browser.newPage()

    // Enforce locale settings for language-sensitive APIs and headers
    await page.setExtraHTTPHeaders({
      "Accept-Language": chromeLang
    })
    const client = await page.target().createCDPSession()
    await client.send("Emulation.setLocaleOverride", { locale: chromeLang })

    const takeDualScreenshot = async (name: string) => {
      await page.screenshot({
        path: path.join(saveDir, `${name}.jpg`),
        type: "jpeg",
        quality: 92
      })
      await page.screenshot({
        path: path.join(saveDir, `${name}.png`),
        type: "png"
      })
    }

    // ----------------------------------------------------
    // SCENE 1: Popup Showcase - Perfect Day Progress
    // ----------------------------------------------------
    console.log("Capturing Scene 1: Popup - Perfect Day...")
    await page.goto(popupUrl, { waitUntil: "networkidle2" })

    const perfectHistory = generateMockSolveHistory()
    await page.evaluate(
      (historyData: SolveHistory, loc: string) => {
        localStorage.setItem("user-locale", loc)
        return new Promise<void>((resolve) => {
          chrome.storage.local.set(
            {
              theme: "dark",
              solveHistory: historyData,
              aiProvider: "gemini",
              aiModel: "gemini-2.5-flash",
              aiApiKey: "AIzaSyD-mocked-gemini-key-for-aesthetic"
            },
            () => {
              chrome.storage.sync.set(
                {
                  theme: "dark",
                  solveHistory: historyData,
                  "sync:userLocale": loc
                },
                resolve
              )
            }
          )
        })
      },
      perfectHistory,
      locale
    )

    await page.reload({ waitUntil: "networkidle2" })
    await page.setViewport({ width: 1280, height: 800 })

    await page.evaluate(
      (
        loc: string,
        extensionConfig: {
          nameMap: Record<string, string>
          subtitleMap: Record<string, string>
        }
      ) => {
        const originalContent = document.body.innerHTML
        document.body.innerHTML = ""

        Object.assign(document.body.style, {
          width: "1280px",
          height: "800px",
          margin: "0",
          padding: "0",
          overflow: "hidden",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          background: "linear-gradient(135deg, #0a66c2 0%, #0b1220 100%)",
          fontFamily:
            "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
        })

        const titleWrapper = document.createElement("div")
        titleWrapper.style.textAlign = "center"
        titleWrapper.style.marginBottom = "24px"
        titleWrapper.style.color = "#ffffff"

        const extensionNameMap = extensionConfig.nameMap
        const subtitleMap = extensionConfig.subtitleMap

        titleWrapper.innerHTML = `
        <h1 style="font-size: 32px; font-weight: 800; margin: 0; letter-spacing: -0.5px; text-shadow: 0 4px 12px rgba(0,0,0,0.15);">${extensionNameMap[loc] || "LinkedIn Games Solver"}</h1>
        <p style="font-size: 15px; color: rgba(255,255,255,0.75); margin: 8px 0 0 0; font-weight: 500;">${subtitleMap[loc] || subtitleMap.en}</p>
      `
        document.body.appendChild(titleWrapper)

        const windowFrame = document.createElement("div")
        Object.assign(windowFrame.style, {
          width: "470px",
          height: "550px",
          borderRadius: "14px",
          overflow: "hidden",
          boxShadow: "0 30px 60px -15px rgba(0, 0, 0, 0.6)",
          border: "1px solid rgba(255, 255, 255, 0.15)",
          background: "#1d2226",
          display: "flex",
          flexDirection: "column"
        })

        const macHeader = document.createElement("div")
        Object.assign(macHeader.style, {
          height: "28px",
          background: "#1f2226",
          display: "flex",
          alignItems: "center",
          paddingLeft: "12px",
          gap: "6px",
          borderBottom: "1px solid rgba(255, 255, 255, 0.05)"
        })
        macHeader.innerHTML = `
        <div style="width: 9px; height: 9px; border-radius: 50%; background: #ff5f56;"></div>
        <div style="width: 9px; height: 9px; border-radius: 50%; background: #ffbd2e;"></div>
        <div style="width: 9px; height: 9px; border-radius: 50%; background: #27c93f;"></div>
      `
        windowFrame.appendChild(macHeader)

        const contentContainer = document.createElement("div")
        Object.assign(contentContainer.style, {
          flex: "1",
          overflow: "auto",
          position: "relative"
        })
        contentContainer.innerHTML = originalContent
        windowFrame.appendChild(contentContainer)

        document.body.appendChild(windowFrame)
      },
      locale,
      { nameMap: compiledNameMap, subtitleMap: compiledSubtitleMap }
    )

    await new Promise((r) => setTimeout(r, 1200))
    await takeDualScreenshot("screenshot-1")

    // ----------------------------------------------------
    // SCENE 2: Popup Showcase - Active Board Blinking
    // ----------------------------------------------------
    console.log("Capturing Scene 2: Popup - Active Board Detected...")
    await page.goto(popupUrl, { waitUntil: "networkidle2" })

    const activeHistory = generateMockActiveHistory()
    await page.evaluate(
      (historyData: SolveHistory, loc: string) => {
        localStorage.setItem("user-locale", loc)
        return new Promise<void>((resolve) => {
          chrome.storage.local.set(
            {
              theme: "dark",
              solveHistory: historyData,
              aiProvider: "gemini",
              aiModel: "gemini-2.5-flash",
              aiApiKey: "AIzaSyD-mocked-gemini-key-for-aesthetic"
            },
            () => {
              chrome.storage.sync.set(
                {
                  theme: "dark",
                  solveHistory: historyData,
                  "sync:userLocale": loc
                },
                resolve
              )
            }
          )
        })
      },
      activeHistory,
      locale
    )

    await page.evaluate(() => {
      if (typeof chrome !== "undefined" && chrome.tabs) {
        ;(chrome.tabs as Record<string, unknown>).sendMessage = (
          _tabId: number,
          msg: Record<string, unknown>,
          cb: (response: unknown) => void
        ) => {
          if (msg && msg.action === "detectGame") {
            setTimeout(() => cb({ game: "sudoku" }), 30)
          } else {
            setTimeout(() => cb(null), 30)
          }
        }
      }
    })

    await page.reload({ waitUntil: "networkidle2" })
    await page.setViewport({ width: 1280, height: 800 })

    await page.evaluate(
      (
        loc: string,
        sceneConfig: {
          tagMap: Record<string, string>
          subtitleMap: Record<string, string>
        }
      ) => {
        const originalContent = document.body.innerHTML
        document.body.innerHTML = ""

        Object.assign(document.body.style, {
          width: "1280px",
          height: "800px",
          margin: "0",
          padding: "0",
          overflow: "hidden",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          background: "linear-gradient(135deg, #0f766e 0%, #0b1220 100%)",
          fontFamily:
            "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
        })

        const titleWrapper = document.createElement("div")
        titleWrapper.style.textAlign = "center"
        titleWrapper.style.marginBottom = "24px"
        titleWrapper.style.color = "#ffffff"

        const tagMap = sceneConfig.tagMap
        const subtitleMap = sceneConfig.subtitleMap

        titleWrapper.innerHTML = `
        <span style="font-size: 11px; font-weight: 800; background: rgba(255,255,255,0.12); color: #ffffff; padding: 4px 10px; border-radius: 20px; letter-spacing: 1px; display: inline-block; margin-bottom: 8px;">${tagMap[loc] || "NATIVE INTEGRATION"}</span>
        <h1 style="font-size: 32px; font-weight: 800; margin: 0; letter-spacing: -0.5px; text-shadow: 0 4px 12px rgba(0,0,0,0.15);">${subtitleMap[loc] || subtitleMap.en}</h1>
      `
        document.body.appendChild(titleWrapper)

        const windowFrame = document.createElement("div")
        Object.assign(windowFrame.style, {
          width: "470px",
          height: "550px",
          borderRadius: "14px",
          overflow: "hidden",
          boxShadow: "0 30px 60px -15px rgba(0, 0, 0, 0.6)",
          border: "1px solid rgba(255, 255, 255, 0.15)",
          background: "#1d2226",
          display: "flex",
          flexDirection: "column"
        })

        const macHeader = document.createElement("div")
        Object.assign(macHeader.style, {
          height: "28px",
          background: "#1f2226",
          display: "flex",
          alignItems: "center",
          paddingLeft: "12px",
          gap: "6px",
          borderBottom: "1px solid rgba(255, 255, 255, 0.05)"
        })
        macHeader.innerHTML = `
        <div style="width: 9px; height: 9px; border-radius: 50%; background: #ff5f56;"></div>
        <div style="width: 9px; height: 9px; border-radius: 50%; background: #ffbd2e;"></div>
        <div style="width: 9px; height: 9px; border-radius: 50%; background: #27c93f;"></div>
      `
        windowFrame.appendChild(macHeader)

        const contentContainer = document.createElement("div")
        Object.assign(contentContainer.style, {
          flex: "1",
          overflow: "auto",
          position: "relative"
        })
        contentContainer.innerHTML = originalContent
        windowFrame.appendChild(contentContainer)

        document.body.appendChild(windowFrame)
      },
      locale,
      { tagMap: compiledScene3.tagMap, subtitleMap: compiledScene3.subtitleMap }
    )

    await new Promise((r) => setTimeout(r, 1200))
    await takeDualScreenshot("screenshot-2")

    // ----------------------------------------------------
    // SCENE 3: Desktop Dashboard - History & Statistics
    // ----------------------------------------------------
    console.log("Capturing Scene 3: Desktop Dashboard - Stats...")
    await page.goto(dashboardUrl, { waitUntil: "networkidle2" })

    await page.evaluate(
      (historyData: SolveHistory, loc: string) => {
        localStorage.setItem("user-locale", loc)
        return new Promise<void>((resolve) => {
          chrome.storage.local.set(
            {
              theme: "dark",
              solveHistory: historyData,
              aiProvider: "gemini",
              aiModel: "gemini-2.5-flash",
              aiApiKey: "AIzaSyD-mocked-gemini-key-for-aesthetic"
            },
            () => {
              chrome.storage.sync.set(
                {
                  theme: "dark",
                  solveHistory: historyData,
                  "sync:userLocale": loc
                },
                resolve
              )
            }
          )
        })
      },
      perfectHistory,
      locale
    )

    await page.reload({ waitUntil: "networkidle2" })
    await page.setViewport({ width: 1280, height: 800 })

    await new Promise((r) => setTimeout(r, 1200))
    await takeDualScreenshot("screenshot-3")

    // ----------------------------------------------------
    // SCENE 4: Desktop Dashboard - Options AI Config Settings
    // ----------------------------------------------------
    console.log("Capturing Scene 4: Desktop Dashboard - Options settings...")
    await page.goto(dashboardUrl, { waitUntil: "networkidle2" })

    await page.evaluate(
      (historyData: SolveHistory, loc: string) => {
        localStorage.setItem("user-locale", loc)
        return new Promise<void>((resolve) => {
          chrome.storage.local.set(
            {
              theme: "dark",
              solveHistory: historyData,
              aiProvider: "gemini",
              aiModel: "gemini-2.5-flash",
              aiApiKey: "AIzaSyD-mocked-gemini-key-for-aesthetic"
            },
            () => {
              chrome.storage.sync.set(
                {
                  theme: "dark",
                  solveHistory: historyData,
                  "sync:userLocale": loc
                },
                resolve
              )
            }
          )
        })
      },
      perfectHistory,
      locale
    )

    await page.reload({ waitUntil: "networkidle2" })
    await page.setViewport({ width: 1280, height: 800 })

    await page.evaluate(() => {
      // Find settings button language-agnostically by checking for the Lucide Settings icon
      const settingsIcon = document.querySelector("svg.lucide-settings")
      if (settingsIcon) {
        const btn = settingsIcon.closest("button")
        if (btn) {
          btn.click()
          return
        }
      }

      // Fallback: search for buttons containing common text combinations
      const buttons = Array.from(document.querySelectorAll("button"))
      const settingsBtn = buttons.find(
        (b) =>
          b.querySelector("svg.lucide-settings") ||
          b.textContent?.includes("AI Config") ||
          b.textContent?.includes("Options") ||
          b.textContent?.includes("Optionen") ||
          b.textContent?.includes("Einstellungen") ||
          b.textContent?.includes("Ayarlar") ||
          b.textContent?.includes("Configur") ||
          b.textContent?.includes("Configuration") ||
          b.textContent?.includes("Konfiguration") ||
          b.textContent?.includes("设置")
      )
      if (settingsBtn) {
        settingsBtn.click()
      }
    })

    await new Promise((r) => setTimeout(r, 1000))
    await takeDualScreenshot("screenshot-4")

    // ----------------------------------------------------
    // SCENE 5: Side Panel Showcase
    // ----------------------------------------------------
    console.log("Capturing Scene 5: Side Panel Showcase...")
    const sidepanelUrl = `chrome-extension://${extensionId}/sidepanel.html`
    await page.goto(sidepanelUrl, { waitUntil: "networkidle2" })

    await page.evaluate(
      (historyData: SolveHistory, loc: string) => {
        localStorage.setItem("user-locale", loc)
        return new Promise<void>((resolve) => {
          chrome.storage.local.set(
            {
              theme: "dark",
              solveHistory: historyData,
              aiProvider: "gemini",
              aiModel: "gemini-2.5-flash",
              aiApiKey: "AIzaSyD-mocked-gemini-key-for-aesthetic"
            },
            () => {
              chrome.storage.sync.set(
                {
                  theme: "dark",
                  solveHistory: historyData,
                  "sync:userLocale": loc
                },
                resolve
              )
            }
          )
        })
      },
      activeHistory,
      locale
    )

    await page.evaluate(`() => {
      if (typeof chrome !== "undefined" && chrome.tabs) {
        chrome.tabs.sendMessage = function(_tabId, msg, cb) {
          if (msg && msg.action === "detectGame") {
            setTimeout(function() { cb({ game: "queens" }); }, 30);
          } else {
            setTimeout(function() { cb(null); }, 30);
          }
        };
      }
    }`)

    await page.reload({ waitUntil: "networkidle2" })
    await page.setViewport({ width: 1280, height: 800 })

    await page.evaluate(
      (
        loc: string,
        sceneConfig: {
          tagMap: Record<string, string>
          subtitleMap: Record<string, string>
        }
      ) => {
        const originalContent = document.body.innerHTML
        document.body.innerHTML = ""

        Object.assign(document.body.style, {
          width: "1280px",
          height: "800px",
          margin: "0",
          padding: "0",
          overflow: "hidden",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          background: "linear-gradient(135deg, #1e3a8a 0%, #0b1220 100%)",
          fontFamily:
            "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
        })

        const titleWrapper = document.createElement("div")
        titleWrapper.style.textAlign = "center"
        titleWrapper.style.marginBottom = "20px"
        titleWrapper.style.color = "#ffffff"

        const tagMap = sceneConfig.tagMap
        const subtitleMap = sceneConfig.subtitleMap

        titleWrapper.innerHTML = `
        <span style="font-size: 11px; font-weight: 800; background: rgba(255,255,255,0.12); color: #ffffff; padding: 4px 10px; border-radius: 20px; letter-spacing: 1px; display: inline-block; margin-bottom: 8px;">${tagMap[loc] || "SIDEBAR INTEGRATION"}</span>
        <h1 style="font-size: 30px; font-weight: 800; margin: 0; letter-spacing: -0.5px; text-shadow: 0 4px 12px rgba(0,0,0,0.15);">${subtitleMap[loc] || subtitleMap.en}</h1>
      `
        document.body.appendChild(titleWrapper)

        const browserMock = document.createElement("div")
        Object.assign(browserMock.style, {
          width: "1100px",
          height: "600px",
          borderRadius: "14px",
          overflow: "hidden",
          boxShadow: "0 30px 60px -15px rgba(0, 0, 0, 0.6)",
          border: "1px solid rgba(255, 255, 255, 0.15)",
          background: "#1d2226",
          display: "flex",
          flexDirection: "column"
        })

        const browserHeader = document.createElement("div")
        Object.assign(browserHeader.style, {
          height: "36px",
          background: "#1f2226",
          display: "flex",
          alignItems: "center",
          padding: "0 16px",
          borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
          justifyContent: "space-between"
        })

        const windowControls = `
        <div style="display: flex; gap: 6px;">
          <div style="width: 9px; height: 9px; border-radius: 50%; background: #ff5f56;"></div>
          <div style="width: 9px; height: 9px; border-radius: 50%; background: #ffbd2e;"></div>
          <div style="width: 9px; height: 9px; border-radius: 50%; background: #27c93f;"></div>
        </div>
      `
        const urlBar = `
        <div style="background: rgba(0, 0, 0, 0.25); border-radius: 6px; font-size: 10px; color: rgba(255,255,255,0.65); padding: 4px 120px; border: 1px solid rgba(255, 255, 255, 0.05); font-family: monospace;">
          linkedin.com/games/queens/
        </div>
      `
        browserHeader.innerHTML = `${windowControls}${urlBar}<div style="width: 38px;"></div>`
        browserMock.appendChild(browserHeader)

        const splitWorkspace = document.createElement("div")
        Object.assign(splitWorkspace.style, {
          flex: "1",
          display: "flex",
          overflow: "hidden"
        })

        // Left column: Mock LinkedIn Queens board
        const mockGamePane = document.createElement("div")
        Object.assign(mockGamePane.style, {
          width: "760px",
          height: "100%",
          background: "#090d16",
          display: "flex",
          flexDirection: "column",
          padding: "24px",
          boxSizing: "border-box",
          borderRight: "1px solid rgba(255, 255, 255, 0.1)"
        })

        // Generate 8x8 colored cells
        const regionsColors = [
          "#1e3a8a",
          "#1e3a8a",
          "#1e3a8a",
          "#0369a1",
          "#0369a1",
          "#0369a1",
          "#0369a1",
          "#0369a1",
          "#1d4ed8",
          "#1e3a8a",
          "#1e3a8a",
          "#0369a1",
          "#0284c7",
          "#0284c7",
          "#0f766e",
          "#0f766e",
          "#1d4ed8",
          "#1d4ed8",
          "#1e3a8a",
          "#0284c7",
          "#0284c7",
          "#0f766e",
          "#0f766e",
          "#0f766e",
          "#3b82f6",
          "#1d4ed8",
          "#1d4ed8",
          "#6366f1",
          "#6366f1",
          "#4f46e5",
          "#0f766e",
          "#0f766e",
          "#3b82f6",
          "#3b82f6",
          "#1d4ed8",
          "#6366f1",
          "#4f46e5",
          "#4f46e5",
          "#4f46e5",
          "#0f766e",
          "#059669",
          "#3b82f6",
          "#6366f1",
          "#6366f1",
          "#4f46e5",
          "#065f46",
          "#065f46",
          "#065f46",
          "#059669",
          "#059669",
          "#059669",
          "#059669",
          "#065f46",
          "#065f46",
          "#065f46",
          "#065f46",
          "#059669",
          "#059669",
          "#059669",
          "#065f46",
          "#065f46",
          "#065f46",
          "#065f46",
          "#065f46"
        ]

        let cellsHtml = ""
        for (let i = 0; i < 64; i++) {
          const r = Math.floor(i / 8)
          const c = i % 8
          const color = regionsColors[i]
          let txt = ""
          if (r === 0 && c === 3) txt = "👑"
          else if (
            (r === 0 && Math.abs(c - 3) === 1) ||
            (c === 3 && Math.abs(r - 0) === 1)
          )
            txt = "×"
          cellsHtml += `
          <div style="background: ${color}; border-radius: 4px; display: flex; align-items: center; justify-content: center; font-size: 16px; font-weight: bold; color: #ffffff; cursor: default;">${txt}</div>
        `
        }

        mockGamePane.innerHTML = `
        <div style="display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid rgba(255,255,255,0.08); padding-bottom: 10px; margin-bottom: 20px;">
          <div>
            <h2 style="font-size: 18px; font-weight: 800; margin: 0; color: #ffffff;">LinkedIn Queens</h2>
            <p style="font-size: 11px; color: rgba(255,255,255,0.55); margin: 3px 0 0 0;">Crown each region. One queen per row, column, and colored region.</p>
          </div>
          <div style="background: rgba(255, 255, 255, 0.08); border-radius: 20px; padding: 4px 10px; font-size: 9px; font-weight: bold; color: rgba(255,255,255,0.85); display: flex; align-items: center; gap: 4px;">
            <span style="width: 5px; height: 5px; border-radius: 50%; background: #0a66c2; display: inline-block;"></span> Active Board
          </div>
        </div>
        <div style="flex: 1; display: flex; align-items: center; justify-content: center;">
          <div style="display: grid; grid-template-columns: repeat(8, 38px); grid-template-rows: repeat(8, 38px); gap: 2px; background: rgba(0, 0, 0, 0.3); padding: 6px; border-radius: 12px; border: 1px solid rgba(255, 255, 255, 0.08);">
            ${cellsHtml}
          </div>
        </div>
      `
        splitWorkspace.appendChild(mockGamePane)

        // Right column: Elongated Side Panel
        const mockSidepanelPane = document.createElement("div")
        Object.assign(mockSidepanelPane.style, {
          width: "340px",
          height: "100%",
          overflow: "auto",
          position: "relative",
          background: "#1d2226"
        })
        mockSidepanelPane.innerHTML = originalContent
        splitWorkspace.appendChild(mockSidepanelPane)

        browserMock.appendChild(splitWorkspace)
        document.body.appendChild(browserMock)
      },
      locale,
      compiledScene4
    )

    await new Promise((r) => setTimeout(r, 1200))
    await takeDualScreenshot("screenshot-5")

    // ----------------------------------------------------
    // SCENE 6: DevTools diagnostics and telemetry panel
    // ----------------------------------------------------
    console.log("Capturing Scene 6: DevTools diagnostics panel...")
    const devtoolsUrl = `chrome-extension://${extensionId}/devtools-panel.html`
    await page.goto(devtoolsUrl, { waitUntil: "networkidle2" })

    await page.evaluate(`() => {
      // Mock window.chrome.devtools
      var mockChrome = window.chrome || {};
      mockChrome.devtools = {
        inspectedWindow: {
          tabId: 42,
          eval: function(script, callback) {
            if (script.includes("window.location.href")) {
              callback("https://www.linkedin.com/games/queens/");
            } else if (script.includes("Queens") || script.includes("queens")) {
              callback("Queens");
            } else if (script.includes("cellInspectScript") || script.includes("cellSelectors")) {
              // Beautiful 8x8 colored cells mockup for Queens F12 Inspector
              var mockCells = [];
              var regionsColors = [
                "rgba(30, 58, 138, 0.8)",   // blue
                "rgba(3, 105, 161, 0.8)",   // light blue
                "rgba(29, 78, 216, 0.8)",   // dark blue
                "rgba(2, 132, 199, 0.8)",   // sky
                "rgba(15, 118, 110, 0.8)",  // teal
                "rgba(59, 130, 246, 0.8)",  // indigo
                "rgba(99, 102, 241, 0.8)",  // violet
                "rgba(6, 95, 70, 0.8)"      // green
              ];
              for (var i = 0; i < 64; i++) {
                var r = Math.floor(i / 8);
                var c = i % 8;
                var color = regionsColors[r % regionsColors.length];
                var text = "";
                var ariaLabel = "cell region";
                if (r === 0 && c === 3) {
                  text = "👑";
                  ariaLabel = "Queen";
                } else if ((r === 0 && Math.abs(c - 3) === 1) || (c === 3 && Math.abs(r - 0) === 1)) {
                  text = "x";
                  ariaLabel = "empty marker";
                }
                mockCells.push({
                  id: "cell-position-" + r + "-" + c,
                  text: text,
                  ariaLabel: ariaLabel,
                  disabled: false,
                  color: color
                });
              }
              callback(mockCells);
            } else if (script.includes("mainHtmlScript")) {
              callback("<main class='queens-board'>...</main>");
            } else {
              callback(null);
            }
          }
        }
      };

      // Mock window.chrome.storage.session
      mockChrome.storage = mockChrome.storage || {};
      mockChrome.storage.session = {
        get: function(key, callback) {
          callback({
            solverLogs: [
              { timestamp: "12:04:15", type: "info", message: "Queens solver engine initialized successfully." },
              { timestamp: "12:04:16", type: "log", message: "Scanning grid DOM looking for .queens-cell nodes..." },
              { timestamp: "12:04:16", type: "info", message: "Found 64 active board cells with 8 color regions." },
              { timestamp: "12:04:17", type: "log", message: "Formulating integer programming constraint matrix..." },
              { timestamp: "12:04:17", type: "log", message: "Running back-tracking solver thread (pacing: Stealth Mode)..." },
              { timestamp: "12:04:18", type: "info", message: "Validating column/row constraints: no conflicts found." },
              { timestamp: "12:04:19", type: "info", message: "Placing Queen at cell (0, 3) in region 1." },
              { timestamp: "12:04:19", type: "log", message: "Triggering mouse clicks on LinkedIn game grid..." },
              { timestamp: "12:04:20", type: "info", message: "Board solved successfully in 4.8 seconds! 🎉" }
            ]
          });
        },
        remove: function(key) { return Promise.resolve(); },
        onChanged: {
          addListener: function() {},
          removeListener: function() {}
        }
      };
      window.chrome = mockChrome;
    }`)

    await page.reload({ waitUntil: "networkidle2" })
    await page.setViewport({ width: 1280, height: 800 })

    await page.evaluate(
      (
        loc: string,
        sceneConfig: {
          tagMap: Record<string, string>
          subtitleMap: Record<string, string>
        }
      ) => {
        const originalContent = document.body.innerHTML
        document.body.innerHTML = ""

        Object.assign(document.body.style, {
          width: "1280px",
          height: "800px",
          margin: "0",
          padding: "0",
          overflow: "hidden",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          background: "linear-gradient(135deg, #4f46e5 0%, #09090b 100%)",
          fontFamily:
            "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
        })

        const titleWrapper = document.createElement("div")
        titleWrapper.style.textAlign = "center"
        titleWrapper.style.marginBottom = "20px"
        titleWrapper.style.color = "#ffffff"

        const tagMap = sceneConfig.tagMap
        const subtitleMap = sceneConfig.subtitleMap

        titleWrapper.innerHTML = `
        <span style="font-size: 11px; font-weight: 800; background: rgba(255,255,255,0.12); color: #ffffff; padding: 4px 10px; border-radius: 20px; letter-spacing: 1px; display: inline-block; margin-bottom: 8px;">${tagMap[loc] || "DIAGNOSTICS & TELEMETRY"}</span>
        <h1 style="font-size: 30px; font-weight: 800; margin: 0; letter-spacing: -0.5px; text-shadow: 0 4px 12px rgba(0,0,0,0.15);">${subtitleMap[loc] || subtitleMap.en}</h1>
      `
        document.body.appendChild(titleWrapper)

        const f12Mock = document.createElement("div")
        Object.assign(f12Mock.style, {
          width: "1000px",
          height: "560px",
          borderRadius: "14px",
          overflow: "hidden",
          boxShadow: "0 30px 60px -15px rgba(0, 0, 0, 0.6)",
          border: "1px solid rgba(255, 255, 255, 0.15)",
          background: "#09090b",
          display: "flex",
          flexDirection: "column"
        })

        const f12Header = document.createElement("div")
        Object.assign(f12Header.style, {
          height: "36px",
          background: "#18181b",
          display: "flex",
          alignItems: "center",
          padding: "0 16px",
          borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
          gap: "16px"
        })

        const windowControls = `
        <div style="display: flex; gap: 6px; margin-right: 12px;">
          <div style="width: 9px; height: 9px; border-radius: 50%; background: #ff5f56;"></div>
          <div style="width: 9px; height: 9px; border-radius: 50%; background: #ffbd2e;"></div>
          <div style="width: 9px; height: 9px; border-radius: 50%; background: #27c93f;"></div>
        </div>
      `
        const devtoolsTab = `
        <div style="display: flex; items-center; font-size: 10px; gap: 12px; color: rgba(255,255,255,0.4); font-weight: bold;">
          <span>Elements</span>
          <span>Console</span>
          <span>Sources</span>
          <span>Network</span>
          <span style="color: #3b82f6; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; margin-bottom: -8px;">LinkedIn Games Solver</span>
        </div>
      `
        f12Header.innerHTML = `${windowControls}${devtoolsTab}`
        f12Mock.appendChild(f12Header)

        const f12Content = document.createElement("div")
        Object.assign(f12Content.style, {
          flex: "1",
          overflow: "hidden",
          position: "relative"
        })
        f12Content.innerHTML = originalContent
        f12Mock.appendChild(f12Content)

        document.body.appendChild(f12Mock)
      },
      locale,
      compiledScene6
    )

    await new Promise((r) => setTimeout(r, 1200))
    await takeDualScreenshot("screenshot-6")
  } catch (error) {
    console.error(`Error generating screenshots for locale [${locale}]:`, error)
  } finally {
    await browser.close()
  }
}

// --- Global Social Previews Generator ---
function generateSocialPreviews(): void {
  const socialDir = path.join(outDir, "social")
  ensureDir(socialDir)

  const globalLarge = path.join(socialDir, "social-1280x640.jpg")
  const globalSmall = path.join(socialDir, "social-640x320.jpg")

  run(
    [
      imageMagickCmd,
      "-size",
      "1280x640",
      q("gradient:#0a66c2-#0f172a"),
      "-gravity",
      "center",
      "-fill",
      q("#0b1220"),
      "-draw",
      q("roundrectangle 80,80 1200,560 28,28"),
      "\\(",
      q(path.join(tmpDir, "tango-220.png")),
      "-resize",
      "260x260",
      "\\)",
      "-gravity",
      "west",
      "-geometry",
      "+160+0",
      "-composite",
      "\\(",
      q(path.join(tmpDir, "queens-220.png")),
      "-resize",
      "260x260",
      "\\)",
      "-gravity",
      "center",
      "-geometry",
      "+0+0",
      "-composite",
      "\\(",
      q(path.join(tmpDir, "icon-300.png")),
      "-resize",
      "180x180",
      "\\)",
      "-gravity",
      "east",
      "-geometry",
      "+160+0",
      "-composite",
      "-strip",
      "-quality",
      "92",
      q(globalLarge)
    ].join(" ")
  )

  run(
    [
      imageMagickCmd,
      q(globalLarge),
      "-resize",
      "640x320",
      "-strip",
      "-quality",
      "92",
      q(globalSmall)
    ].join(" ")
  )
}

// --- Localized Social Previews Generator ---
async function generateLocalizedSocialPreviews(): Promise<void> {
  if (!existsSync(localesDir)) {
    return
  }

  const locales = readdirSync(localesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)

  const fallbackMessages = readLocaleMessages("en")
  const globalLarge = path.join(outDir, "social", "social-1280x640.jpg")

  if (!existsSync(globalLarge)) {
    console.error("Global social preview template not found! Cannot localize.")
    return
  }

  for (const locale of locales) {
    const localeSocialDir = path.join(localizedDir, locale, "social")
    ensureDir(localeSocialDir)

    const msgs = readLocaleMessages(locale)
    const title = truncateText(
      cleanText(
        getMessageValue(msgs, "extensionName") ||
          getMessageValue(msgs, "title") ||
          getMessageValue(fallbackMessages, "extensionName") ||
          getMessageValue(fallbackMessages, "title") ||
          "LinkedIn Games Solver"
      ),
      48
    )

    const desc = truncateText(
      cleanText(
        getMessageValue(msgs, "extensionDescription") ||
          getMessageValue(msgs, "subtitle") ||
          getMessageValue(fallbackMessages, "extensionDescription") ||
          getMessageValue(fallbackMessages, "subtitle") ||
          "A helper for LinkedIn Games."
      ),
      100
    )

    const localeFontPath = resolveFontPathForLocale(locale)
    const outLarge = path.join(localeSocialDir, "social-1280x640.jpg")

    await asyncRun(
      [
        imageMagickCmd,
        q(globalLarge),
        "-fill",
        q("rgba(0,0,0,0.45)"),
        "-draw",
        q("roundrectangle 64,448 1216,608 20,20"),
        "-fill",
        q("#ffffff"),
        ...(localeFontPath ? ["-font", q(localeFontPath)] : []),
        "-pointsize",
        "44",
        "-gravity",
        "southwest",
        "-annotate",
        "+88+120",
        q(title),
        "-pointsize",
        "26",
        "-gravity",
        "southwest",
        "-annotate",
        "+88+68",
        q(desc),
        "-strip",
        "-quality",
        "92",
        q(outLarge)
      ].join(" ")
    )

    await asyncRun(
      [
        imageMagickCmd,
        q(outLarge),
        "-resize",
        "640x320",
        "-strip",
        "-quality",
        "92",
        q(path.join(localeSocialDir, "social-640x320.jpg"))
      ].join(" ")
    )
  }
}

// --- Store Description Markdown Generator ---
function generateStoreDescriptions(localeFilter?: string[] | null): void {
  console.log("\nGenerating store descriptions...")
  let descriptions: Record<string, string> = compiledDescriptions

  if (localeFilter) {
    descriptions = Object.fromEntries(
      Object.entries(descriptions).filter(([loc]) => localeFilter.includes(loc))
    )
  }

  // Save global/English description for backward compatibility
  const enMessages = readLocaleMessages("en")
  const enDisclaimer = getMessageValue(enMessages, "disclaimerText")
  const enContent =
    descriptions.en + (enDisclaimer ? `\n\n---\n\n*${enDisclaimer}*` : "")
  ensureDir(path.join(outDir, "global"))
  writeFileSync(path.join(outDir, "global", "description.md"), enContent)

  // Save localized descriptions (including English)
  for (const [locale, content] of Object.entries(descriptions)) {
    const localeMessages = readLocaleMessages(locale)
    const localeDisclaimer = getMessageValue(localeMessages, "disclaimerText")
    const localizedContent =
      content + (localeDisclaimer ? `\n\n---\n\n*${localeDisclaimer}*` : "")

    const localePath = path.join(localizedDir, locale)
    ensureDir(localePath)
    writeFileSync(path.join(localePath, "description.md"), localizedContent)
  }
  console.log(
    "Store descriptions generated successfully in both global and localized folders!"
  )
}

async function pMap<T>(
  items: T[],
  fn: (item: T) => Promise<void>,
  concurrency: number
): Promise<void> {
  let index = 0
  const worker = async (): Promise<void> => {
    while (index < items.length) {
      const current = index++
      try {
        await fn(items[current])
      } catch (error) {
        console.error(`Error processing ${items[current]}:`, error)
      }
    }
  }
  const workers = Array.from(
    { length: Math.min(concurrency, items.length) },
    () => worker()
  )
  await Promise.all(workers)
}

// --- Main Program Execution ---
async function main(): Promise<void> {
  const args = process.argv.slice(2)
  const descriptionsOnly = args.includes("--descriptions")

  const localesArgIndex = args.indexOf("--locales")
  const localeFilter: string[] | null =
    localesArgIndex !== -1 && args[localesArgIndex + 1]
      ? args[localesArgIndex + 1]
          .split(",")
          .map((l) => l.trim())
          .filter(Boolean)
      : null

  if (descriptionsOnly) {
    console.log(
      "Descriptions-only mode. Generating Markdown store descriptions...\n"
    )
    generateStoreDescriptions(localeFilter)
    console.log("\nSuccessfully generated Markdown store descriptions!")
    return
  }

  const hasRsvg = hasTool("rsvg-convert")
  const hasMagick = hasTool(imageMagickCmd)

  if (localeFilter) {
    console.log(
      "Locale filter detected — only regenerating specified locales, preserving existing assets for others."
    )
  } else {
    console.log("Completely clearing store-assets folder for a clean slate...")
    if (existsSync(outDir)) {
      if (hasRsvg && hasMagick) {
        rmSync(outDir, { recursive: true, force: true })
      }
    }
  }

  // Build target directories fresh
  ensureDir(outDir)
  ensureDir(path.join(outDir, "global"))
  ensureDir(globalScreenshotsDir)
  ensureDir(localizedDir)

  if (!hasRsvg || !hasMagick) {
    console.log(
      "\n⚠️ WARNING: 'rsvg-convert' or 'ImageMagick' is missing in PATH. Skipping visual assets generation."
    )
    console.log("Generating Markdown store descriptions directly...\n")
    generateStoreDescriptions()
    console.log("\nSuccessfully generated Markdown store descriptions!")
    return
  }

  // Step 1: Pre-render vector assets and compose store icons
  console.log("Preparing icons and rendering basic assets...")
  prepIconRenders()
  generateStoreIcon()
  generateExtensionIcons()

  // Step 2: Ensure built extension exists
  console.log("Ensuring built extension target exists...")
  if (!existsSync(buildDir)) {
    console.log("Building extension...")
    await asyncRun("npx wxt build")
  }

  // Step 3: Capture beautifully mock-fed browser screenshots (Global/English)
  // This must run before promo composites so screenshots exist for mockups
  await captureScreenshots("en")

  // Step 4: Compose premium promo banners and social previews with embedded screenshots
  console.log("Generating premium promo tiles and social previews...")
  await Promise.all([
    generatePromoSmall("global"),
    generatePromoMarquee("global"),
    generatePromoSmall("en"),
    generatePromoMarquee("en"),
    generateSocialPreviews()
  ])

  // Step 5: Capture screenshots and generate localized promotional tiles for all other localized directories
  const allLocales = readdirSync(localesDir, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory() && dirent.name !== "en")
    .map((dirent) => dirent.name)
  const locales = localeFilter
    ? allLocales.filter((l) => localeFilter.includes(l))
    : allLocales
  await pMap(
    locales,
    async (locale) => {
      await captureScreenshots(locale)
      await generatePromoSmall(locale)
      await generatePromoMarquee(locale)
    },
    Math.ceil(locales.length / 10)
  )

  // Step 6: Render localized social media OG cards using ImageMagick
  console.log("\nGenerating localized social headers...")
  await generateLocalizedSocialPreviews()

  // Step 7: Generate clean Markdown store descriptions for all locales
  generateStoreDescriptions(localeFilter)

  // Cleanup temp files
  rmSync(tmpDir, { recursive: true, force: true })

  console.log("\n=======================================================")
  console.log("Successfully generated all Chrome Web Store assets!")
  console.log("=======================================================")
  console.log("- Store icon: store-assets/store-icon-128.png")
  console.log("- Global promo tiles: store-assets/global/*.jpg")
  console.log(
    "- Global screenshots: store-assets/global/screenshots/*.{jpg,png}"
  )
  console.log(
    "- Localized screenshots: store-assets/localized/<locale>/screenshots/*.{jpg,png}"
  )
  console.log("- Social media card pre-renders: store-assets/social/*.jpg")
  console.log(
    "- Localized social media: store-assets/localized/<locale>/social/*.jpg"
  )
  console.log(
    "- Store listings text (Markdown): store-assets/global/description.md & store-assets/localized/<locale>/description.md"
  )
  console.log("All screenshots are beautifully rendered inside a browser!")
  console.log("=======================================================")
}

main().catch(console.error)
